# Generated by Django 4.2.14 on 2025-03-10 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foreign_Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=48, verbose_name='foreign word')),
                ('create_date', models.DateField(auto_now_add=True)),
                ('appearance_count', models.IntegerField(default=0)),
                ('right_answer', models.IntegerField(default=0)),
                ('last_appearance', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Words_Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_name', models.CharField(max_length=32, unique=True)),
                ('create_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Translate_Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=48)),
                ('foreign_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words_polls.foreign_word')),
            ],
        ),
        migrations.AddField(
            model_name='foreign_word',
            name='words_collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words_polls.words_collection'),
        ),
    ]
