# Generated by Django 4.2.14 on 2025-04-03 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('words_polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foreign_word',
            options={'ordering': ['create_date']},
        ),
        migrations.AlterModelOptions(
            name='words_collection',
            options={'ordering': ['-create_date']},
        ),
        migrations.AlterField(
            model_name='foreign_word',
            name='words_collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foreign_words', to='words_polls.words_collection'),
        ),
        migrations.AlterField(
            model_name='translate_word',
            name='foreign_word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translate_words', to='words_polls.foreign_word'),
        ),
        migrations.AlterModelTable(
            name='foreign_word',
            table='foreign_words',
        ),
        migrations.AlterModelTable(
            name='translate_word',
            table='translate_words',
        ),
        migrations.AlterModelTable(
            name='words_collection',
            table='words_collection',
        ),
    ]
