# Generated by Django 4.2.14 on 2025-04-15 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('words_polls', '0002_alter_foreign_word_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='words_collection',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='words_collection',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_collections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='words_collection',
            name='slug',
            field=models.SlugField(blank=True, max_length=180, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='words_collection',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='words_collections', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='words_collection',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('shared', 'Shared'), ('private', 'Private')], default='private', max_length=10),
        ),
        migrations.AlterField(
            model_name='words_collection',
            name='collection_name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
